baseURL = "https://blog.fireflylabs.ai"
title = "Ryan's Musings"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Your site description"
  copyright = "Built using Hugo Framework (with Etch theme) on Cloudflare Pages"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true